export const projects = [
  {
    title: 'Odun pizza',
    description: "Using React,Next js,Mongoose & MongoDB i learnt how to build a Full Stack  Application - from start to finish. This app is called odun and it is a functioning food ordering site   ",
    image: '/images/foodH.png',
    tags: ['MongoDB','Next js','React','Paypal',"Contex API",],
    source: 'https://github.com/olaoluwaayanbola/odun-pizza',
    visit: 'https://github.com/olaoluwaayanbola/odun-pizza',
    id: 0,
  },
  {
    title: 'Asotuntun.c',
    description: "While building this project i learnt how to integrate Context API into a react application and learnt one of the best ways to authenticate routes in react using the Context API",
    image: 'images/ecomHom.jpeg',
    tags: ['React', 'Context API','Firebase Auth','Route Auth'],
    source: 'https://github.com/olaoluwaayanbola/ecommerce/tree/SAVEPOINT/client',
    visit: 'https://asotuntun.netlify.app',
    id: 1,
  },
  {
    title: 'Admin-dashboard',
    description: "This is a react admin dashboard building this app helped me further my knowledge of redux toolkit and some design concept",
    image: '/images/ad1.png',
    tags: ['React','Redux',"MUI",'Recharts','Figma',"SASS"],
    source: 'https://github.com/olaoluwaayanbola/react-admin-dash',
    visit: 'https://react-admin-fxx.netlify.app/',
    id: 2,
  },
  {
    title: 'Netflix-clone',
    description: "This is a netflix clone made with react it was my first react-project ",
    image: 'images/netflix.png',
    tags: ['React', 'React-Router-DOM','MUI','SASS'],
    source: 'https://github.com/olaoluwaayanbola/netflix-clone',
    visit: 'https://netflixclone-one.netlify.app/',
    id: 3,
  },
  {
    title: 'Cryptoverse',
    description: "Cryptoverse is a webapp that provides current crypo data for users the most challenging aspect of builduing this web app was the implementation on the search functinality with the REST API  ",
    image: '/images/cryv.png',
    tags: ['React','Redux toolkit',"ANTD",'Recharts',"Coingecko API"],
    source: 'https://github.com/olaoluwaayanbola/cryptoverse',
    visit: 'https://cryptoverse-fx.netlify.app',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];